-- =================================================================
-- DDUK ERP Custom Sample Data Seed File (Amantea Target Edition)
-- =================================================================
-- 이 파일은 아망티(Amantea) 쇼핑몰 크롤링 시나리오 시연을 위한 
-- 기초 마스터 데이터(거래처, 품목, 초기 재고 등) 작성 템플릿입니다.
--
-- 내일 직접 더미 데이터를 작성하실 때 아래 예시들의 주석(--)을 해제하고
-- 실제 아망티 상품명 및 규격에 맞게 값을 채워 넣으시면 됩니다.
-- =================================================================

-- -----------------------------------------------------------------
-- 1. [거래처 등록 예시] 아망티 공식 도매처 등록
-- -----------------------------------------------------------------
-- INSERT INTO vendors (vendor_code, business_registration_no, name, representative_name, business_type, business_item, contact_name, contact_phone, email, status)
-- VALUES ('V005', '000-00-00000', '(주)아망티', '아망티대표', '도소매', '식음료/차류', '아망티담당', '010-9999-8888', 'support@amantea.co.kr', 'ACTIVE')
-- ON DUPLICATE KEY UPDATE 
--     name = VALUES(name), 
--     representative_name = VALUES(representative_name),
--     updated_at = NOW();

-- -----------------------------------------------------------------
-- 2. [품목 등록 예시] 아망티 크롤링 대상 허브차/홍차 품목 매핑
-- -----------------------------------------------------------------
-- INSERT INTO items (item_code, name, item_type, category, spec, unit, default_vendor_id, standard_cost, unit_price, is_active)
-- VALUES 
--     (
--         'ITM-AMNT-001', 
--         '아망티 얼그레이 홍차 (100T)', 
--         'RAW_MATERIAL', 
--         '원재료', 
--         '100개입/상자 [아망티 직매입]', 
--         'BOX', 
--         (SELECT id FROM vendors WHERE vendor_code = 'V005'), 
--         4500.00,  -- ERP 내부 장부가(기준가)
--         6000.00,  -- ERP 표준 발주단가
--         1
--     ),
--     (
--         'ITM-AMNT-002', 
--         '아망티 루이보스 오렌지 (50T)', 
--         'RAW_MATERIAL', 
--         '원재료', 
--         '50개입/상자 [아망티 직매입]', 
--         'BOX', 
--         (SELECT id FROM vendors WHERE vendor_code = 'V005'), 
--         3200.00, 
--         4500.00, 
--         1
--     )
-- ON DUPLICATE KEY UPDATE 
--     name = VALUES(name), 
--     standard_cost = VALUES(standard_cost), 
--     unit_price = VALUES(unit_price),
--     updated_at = NOW();

-- -----------------------------------------------------------------
-- 3. [초기 재고 매핑 예시] 아망티 품목에 대한 원재료창고(WH-RAW) 초기 재고 등록
-- -----------------------------------------------------------------
-- INSERT INTO inventories (item_id, warehouse_id, current_stock, allocated_stock, safety_stock, average_cost, inventory_value)
-- VALUES 
--     (
--         (SELECT id FROM items WHERE item_code = 'ITM-AMNT-001'),
--         (SELECT id FROM warehouses WHERE warehouse_code = 'WH-RAW'),
--         150, -- 초기 재고 150 박스
--         0, 
--         20, 
--         4500.0000, 
--         675000.0000
--     ),
--     (
--         (SELECT id FROM items WHERE item_code = 'ITM-AMNT-002'),
--         (SELECT id FROM warehouses WHERE warehouse_code = 'WH-RAW'),
--         80, 
--         0, 
--         10, 
--         3200.0000, 
--         256000.0000
--     )
-- ON DUPLICATE KEY UPDATE 
--     current_stock = VALUES(current_stock), 
--     inventory_value = VALUES(inventory_value),
--     updated_at = NOW();

-- -----------------------------------------------------------------
-- 빈 스크립트 실행 에러 방지를 위한 더미 쿼리 (삭제 금지)
-- -----------------------------------------------------------------
SELECT 1;
